---
version: 2
jobs:
  # Job syncs GitHub repository to git.drupal.org.
  sync_drupalorg:
    docker:
      - image: nicksantamaria/drupal_contrib_builder:latest
    working_directory: /data
    environment:
      GIT_MIRROR_URL: |
        nickurbits@git.drupal.org:project/username_enumeration_prevention.git
    steps:
      - checkout
      - run:
          name: Add drupal.org git remote
          command: git remote add drupal "${GIT_MIRROR_URL}"
      - run:
          name: Push to drupal.org git remote
          command: git push drupal "${CIRCLE_BRANCH:-refs/tags/${CIRCLE_TAG}}"

  # Job performs code style / validation tasks.
  lint:
    docker:
      - image: nicksantamaria/drupal_contrib_builder:latest
    working_directory: /data
    steps:
      - checkout
      - run:
          name: Ensure yaml files are valid
          command: yamllint /data
      - run:
          name: Ensure json files are valid
          command: cat /data/composer.json | jq .
      - run:
          name: Ensure PHP meets Drupal code standards
          command: |
            phpcs \
              --standard=Drupal \
              --extensions=php,module,inc,install,test,profile,theme,css,info \
              --ignore=*.md \
              /data
      - run:
          name: Test drupal.org packager excludes
          command: bash ./tests/package-excludes/run-test.sh $(pwd)

workflows:
  version: 2
  main:
    jobs:
      - lint
  sync:
    jobs:
      - sync_drupalorg:
          filters:
            tags:
              only: /.*/
            branches:
              only: /[7-9].x-.*/
